DemoApplicationWeb-A/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Models
{
    public class Book
    {
        [JsonPropertyName("id")]
        public int book_id { get; set; }

        [JsonPropertyName("name")]
        public string name { get; set; }

        [JsonPropertyName("image")]
        public string image { get; set; }


        public override string ToString()
        {
            return JsonSerializer.Serialize<Book>(this);
        }
    }
}

DemoApplicationWeb-A/Controllers/BookRecordController.cs
using DemoApplicationWeb_A.Models;
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class BookRecordController : ControllerBase
    {
        JsonFileBookService BookService;
        public BookRecordController(JsonFileBookService bookService)
        {
            this.BookService = bookService;
        }

        [HttpGet]
        public IEnumerable<Book> Get()
        {
            return BookService.getBookRecords();
        }
    }
}

DemoApplicationWeb-A/Controllers/FormHandlerController.cs
using DemoApplicationWeb_A.Models;
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Controllers
{
    [Route("[controller]")]
    public class FormHandlerController : Controller
    {

        JsonFileBookService BookService;
        public FormHandlerController(JsonFileBookService bookService)
        {
            this.BookService = bookService;
        }
        [HttpGet]
        public string Get(int id, string name, string image)
        {
            Book obj = new Book();
            obj.book_id = id;
            obj.name = name;
            obj.image = image;


            BookService.setBookRecords(obj, BookService);
            return "Function Exec";
        }
    }
}

DemoApplicationWeb-A/Controllers/cssController.cs
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class cssController : ControllerBase
    {
        JsonFileBookService BookService;
        public cssController(JsonFileBookService bookService)
        {
            this.BookService = bookService;
        }

        [HttpGet]
        public string Get()
        {
            return BookService.getCss();
        }
    }
}

DemoApplicationWeb-A/Controllers/productController.cs
using DemoApplicationWeb_A.Models;
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class productController : ControllerBase
    {
        JsonFileBookService BookService;
        public productController(JsonFileBookService bookService)
        {
            this.BookService = bookService;
        }

        [HttpGet]
        public IEnumerable<Book> Get()
        {
            return BookService.getBookRecords();
        }
    }
}

DemoApplicationWeb-A/Pages/BookList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DemoApplicationWeb_A.Models;
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoApplicationWeb_A.Pages
{
    public class BookListModel : PageModel
    {
        JsonFileBookService BookService;
        public IEnumerable<Book> Books;

        public BookListModel(JsonFileBookService bookService)
        {
            this.BookService = bookService;
        }
        public void OnGet()
        {
            Books = BookService.getBookRecords();
        }
    }
}

DemoApplicationWeb-A/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DemoApplicationWeb-A/Pages/Index.cshtml.cs
using DemoApplicationWeb_A.Models;
using DemoApplicationWeb_A.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        
        

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            
        }
    }
}

DemoApplicationWeb-A/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoApplicationWeb_A.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DemoApplicationWeb-A/Pages/products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoApplicationWeb_A.Pages
{
    public class productsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

DemoApplicationWeb-A/Pages/BookList.cshtml
@page
@model DemoApplicationWeb_A.Pages.BookListModel
@{
}


<div class="text-center">
    <h1 class="display-4">M-cart</h1>
</div>


<div class="row">
    @foreach (var book in Model.Books)
    {
        <div id="bookContainer" class="col-lg-3 col-md-4 col-sm-1">
            <img id="bookImage" style="width: 100%; height: 100%;" src="@book.image" alt="@book.name" />
            <span id="bookTitle">@book.name</span>
            <span id="bookPrice">Rs. Coming Soon</span>
            <span id="bookQuantity"><input id="quantityInput" type="number" name="bookQuantity" value="" placeholder="0" /></span>
            <span id="bookCartButton"><button id="btn"><span class="fa fa-shopping-cart"></span>Add to Cart</button></span>
        </div>
    }
</div>

DemoApplicationWeb-A/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form action="/FormHandler" method="get">
    <label for="id">Enter product ID:</label>
    <input id="id" type="number" name="id" value="" required />

    <label for="name">Enter product Name:</label>
    <input id="name" type="text" name="name" value="" required />

    <label for="image">Enter image URL:</label>
    <input id="image" type="text" name="image" value="" required />

    <input type="submit" name="submit" value="Submit" />
</form>

DemoApplicationWeb-A/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - M-cart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">M-cart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="css" asp-action="Get">CSS api</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookRecord" asp-action="Get">Products api</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - M-cart - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

DemoApplicationWeb-A/Pages/products.cshtml
@page
@model DemoApplicationWeb_A.Pages.BookListModel
@{
}


<div class="text-center">
    <h1 class="display-4">M-cart</h1>
</div>


<div class="row">
    @foreach (var book in Model.Books)
    {
        <div id="bookContainer" class="col-lg-3 col-md-4 col-sm-1">
            <img id="bookImage" style="width: 100%; height: 100%;" src="@book.image" alt="@book.name" />
            <span id="bookTitle">@book.name</span>
            <span id="bookPrice">Rs. Coming Soon</span>
            <span id="bookQuantity"><input id="quantityInput" type="number" name="bookQuantity" value="" placeholder="0" /></span>
            <span id="bookCartButton"><button id="btn"><span class="fa fa-shopping-cart"></span>Add to Cart</button></span>
        </div>
    }
</div>